name: containers-builder

on:
  push:
    branches:
      - master

env:
  DOG: freddie

jobs:
  build-devices:
    name: devices
    runs-on: ubuntu-20.04
    env:
      COMPONENT: devices
    steps:
      - id: step-0
        name: checkout
        uses: actions/checkout@v2
      - id: step-1
        name: login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR }}
      - id: step-2
        name: dockerimage
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./deployment/Dockerfile.${DEVICES}
          push: true
          tags: ${{ github.sha }}
